version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env


  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    expose: 
      - 5432
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local1234
      POSTGRES_DB: library  
    # command: ["alembic", "upgrade", "head"]


volumes:
  db-data:
  # command: ["alembic", "upgrade", "head"]
